# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "playerconnect-wsdsl"
  s.version = "0.4.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Team SDOD"]
  s.date = "2014-02-07"
  s.description = "A Ruby DSL describing Web Services without implementation details."
  s.email = "sdod"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".rvmrc_example",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/documentation.rb",
    "lib/framework_ext/sinatra.rb",
    "lib/framework_ext/sinatra_controller.rb",
    "lib/inflection.rb",
    "lib/params.rb",
    "lib/params_verification.rb",
    "lib/response.rb",
    "lib/response_exceptions.rb",
    "lib/ws_list.rb",
    "lib/wsdsl.rb",
    "playerconnect-wsdsl.gemspec",
    "spec/hello_world_controller.rb",
    "spec/hello_world_service.rb",
    "spec/params_verification_spec.rb",
    "spec/preferences_service.rb",
    "spec/spec_helper.rb",
    "spec/test_services.rb",
    "spec/wsdsl_sinatra_ext_spec.rb",
    "spec/wsdsl_spec.rb",
    "wsdsl.gemspec"
  ]
  s.homepage = "http://github.com/playerconnect/wsdsl"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Web Service DSL"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, ["= 1.6.4"])
      s.add_development_dependency(%q<rspec>, ["= 2.7.0"])
      s.add_development_dependency(%q<yard>, ["= 0.7.2"])
      s.add_development_dependency(%q<rack-test>, ["= 0.5.7"])
      s.add_development_dependency(%q<sinatra>, ["= 1.2.0"])
    else
      s.add_dependency(%q<jeweler>, ["= 1.6.4"])
      s.add_dependency(%q<rspec>, ["= 2.7.0"])
      s.add_dependency(%q<yard>, ["= 0.7.2"])
      s.add_dependency(%q<rack-test>, ["= 0.5.7"])
      s.add_dependency(%q<sinatra>, ["= 1.2.0"])
    end
  else
    s.add_dependency(%q<jeweler>, ["= 1.6.4"])
    s.add_dependency(%q<rspec>, ["= 2.7.0"])
    s.add_dependency(%q<yard>, ["= 0.7.2"])
    s.add_dependency(%q<rack-test>, ["= 0.5.7"])
    s.add_dependency(%q<sinatra>, ["= 1.2.0"])
  end
end

